development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: taurus_development
  pool: 5
  username: root
  password: root
  socket: /var/run/mysqld/mysqld.sock

production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: ebiz_production
  pool: 5
  host: 192.168.5.10
  username: root
  password: 1jia1mei!@#123
  socket: /var/run/mysqld/mysqld.sock
