require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe CartSkushipsController do

  # This should return the minimal set of attributes required to create a valid
  # CartSkuship. As you add validations to CartSkuship, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all cart_skuships as @cart_skuships" do
      cart_skuship = CartSkuship.create! valid_attributes
      get :index
      assigns(:cart_skuships).should eq([cart_skuship])
    end
  end

  describe "GET show" do
    it "assigns the requested cart_skuship as @cart_skuship" do
      cart_skuship = CartSkuship.create! valid_attributes
      get :show, :id => cart_skuship.id
      assigns(:cart_skuship).should eq(cart_skuship)
    end
  end

  describe "GET new" do
    it "assigns a new cart_skuship as @cart_skuship" do
      get :new
      assigns(:cart_skuship).should be_a_new(CartSkuship)
    end
  end

  describe "GET edit" do
    it "assigns the requested cart_skuship as @cart_skuship" do
      cart_skuship = CartSkuship.create! valid_attributes
      get :edit, :id => cart_skuship.id
      assigns(:cart_skuship).should eq(cart_skuship)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new CartSkuship" do
        expect {
          post :create, :cart_skuship => valid_attributes
        }.to change(CartSkuship, :count).by(1)
      end

      it "assigns a newly created cart_skuship as @cart_skuship" do
        post :create, :cart_skuship => valid_attributes
        assigns(:cart_skuship).should be_a(CartSkuship)
        assigns(:cart_skuship).should be_persisted
      end

      it "redirects to the created cart_skuship" do
        post :create, :cart_skuship => valid_attributes
        response.should redirect_to(CartSkuship.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved cart_skuship as @cart_skuship" do
        # Trigger the behavior that occurs when invalid params are submitted
        CartSkuship.any_instance.stub(:save).and_return(false)
        post :create, :cart_skuship => {}
        assigns(:cart_skuship).should be_a_new(CartSkuship)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        CartSkuship.any_instance.stub(:save).and_return(false)
        post :create, :cart_skuship => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested cart_skuship" do
        cart_skuship = CartSkuship.create! valid_attributes
        # Assuming there are no other cart_skuships in the database, this
        # specifies that the CartSkuship created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        CartSkuship.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => cart_skuship.id, :cart_skuship => {'these' => 'params'}
      end

      it "assigns the requested cart_skuship as @cart_skuship" do
        cart_skuship = CartSkuship.create! valid_attributes
        put :update, :id => cart_skuship.id, :cart_skuship => valid_attributes
        assigns(:cart_skuship).should eq(cart_skuship)
      end

      it "redirects to the cart_skuship" do
        cart_skuship = CartSkuship.create! valid_attributes
        put :update, :id => cart_skuship.id, :cart_skuship => valid_attributes
        response.should redirect_to(cart_skuship)
      end
    end

    describe "with invalid params" do
      it "assigns the cart_skuship as @cart_skuship" do
        cart_skuship = CartSkuship.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        CartSkuship.any_instance.stub(:save).and_return(false)
        put :update, :id => cart_skuship.id, :cart_skuship => {}
        assigns(:cart_skuship).should eq(cart_skuship)
      end

      it "re-renders the 'edit' template" do
        cart_skuship = CartSkuship.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        CartSkuship.any_instance.stub(:save).and_return(false)
        put :update, :id => cart_skuship.id, :cart_skuship => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested cart_skuship" do
      cart_skuship = CartSkuship.create! valid_attributes
      expect {
        delete :destroy, :id => cart_skuship.id
      }.to change(CartSkuship, :count).by(-1)
    end

    it "redirects to the cart_skuships list" do
      cart_skuship = CartSkuship.create! valid_attributes
      delete :destroy, :id => cart_skuship.id
      response.should redirect_to(cart_skuships_url)
    end
  end

end
