require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe CompanyTypesController do

  # This should return the minimal set of attributes required to create a valid
  # CompanyType. As you add validations to CompanyType, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all company_types as @company_types" do
      company_type = CompanyType.create! valid_attributes
      get :index
      assigns(:company_types).should eq([company_type])
    end
  end

  describe "GET show" do
    it "assigns the requested company_type as @company_type" do
      company_type = CompanyType.create! valid_attributes
      get :show, :id => company_type.id
      assigns(:company_type).should eq(company_type)
    end
  end

  describe "GET new" do
    it "assigns a new company_type as @company_type" do
      get :new
      assigns(:company_type).should be_a_new(CompanyType)
    end
  end

  describe "GET edit" do
    it "assigns the requested company_type as @company_type" do
      company_type = CompanyType.create! valid_attributes
      get :edit, :id => company_type.id
      assigns(:company_type).should eq(company_type)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new CompanyType" do
        expect {
          post :create, :company_type => valid_attributes
        }.to change(CompanyType, :count).by(1)
      end

      it "assigns a newly created company_type as @company_type" do
        post :create, :company_type => valid_attributes
        assigns(:company_type).should be_a(CompanyType)
        assigns(:company_type).should be_persisted
      end

      it "redirects to the created company_type" do
        post :create, :company_type => valid_attributes
        response.should redirect_to(CompanyType.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved company_type as @company_type" do
        # Trigger the behavior that occurs when invalid params are submitted
        CompanyType.any_instance.stub(:save).and_return(false)
        post :create, :company_type => {}
        assigns(:company_type).should be_a_new(CompanyType)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        CompanyType.any_instance.stub(:save).and_return(false)
        post :create, :company_type => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested company_type" do
        company_type = CompanyType.create! valid_attributes
        # Assuming there are no other company_types in the database, this
        # specifies that the CompanyType created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        CompanyType.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => company_type.id, :company_type => {'these' => 'params'}
      end

      it "assigns the requested company_type as @company_type" do
        company_type = CompanyType.create! valid_attributes
        put :update, :id => company_type.id, :company_type => valid_attributes
        assigns(:company_type).should eq(company_type)
      end

      it "redirects to the company_type" do
        company_type = CompanyType.create! valid_attributes
        put :update, :id => company_type.id, :company_type => valid_attributes
        response.should redirect_to(company_type)
      end
    end

    describe "with invalid params" do
      it "assigns the company_type as @company_type" do
        company_type = CompanyType.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        CompanyType.any_instance.stub(:save).and_return(false)
        put :update, :id => company_type.id, :company_type => {}
        assigns(:company_type).should eq(company_type)
      end

      it "re-renders the 'edit' template" do
        company_type = CompanyType.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        CompanyType.any_instance.stub(:save).and_return(false)
        put :update, :id => company_type.id, :company_type => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested company_type" do
      company_type = CompanyType.create! valid_attributes
      expect {
        delete :destroy, :id => company_type.id
      }.to change(CompanyType, :count).by(-1)
    end

    it "redirects to the company_types list" do
      company_type = CompanyType.create! valid_attributes
      delete :destroy, :id => company_type.id
      response.should redirect_to(company_types_url)
    end
  end

end
