require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe EscRepliesController do

  # This should return the minimal set of attributes required to create a valid
  # EscReply. As you add validations to EscReply, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all esc_replies as @esc_replies" do
      esc_reply = EscReply.create! valid_attributes
      get :index
      assigns(:esc_replies).should eq([esc_reply])
    end
  end

  describe "GET show" do
    it "assigns the requested esc_reply as @esc_reply" do
      esc_reply = EscReply.create! valid_attributes
      get :show, :id => esc_reply.id
      assigns(:esc_reply).should eq(esc_reply)
    end
  end

  describe "GET new" do
    it "assigns a new esc_reply as @esc_reply" do
      get :new
      assigns(:esc_reply).should be_a_new(EscReply)
    end
  end

  describe "GET edit" do
    it "assigns the requested esc_reply as @esc_reply" do
      esc_reply = EscReply.create! valid_attributes
      get :edit, :id => esc_reply.id
      assigns(:esc_reply).should eq(esc_reply)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new EscReply" do
        expect {
          post :create, :esc_reply => valid_attributes
        }.to change(EscReply, :count).by(1)
      end

      it "assigns a newly created esc_reply as @esc_reply" do
        post :create, :esc_reply => valid_attributes
        assigns(:esc_reply).should be_a(EscReply)
        assigns(:esc_reply).should be_persisted
      end

      it "redirects to the created esc_reply" do
        post :create, :esc_reply => valid_attributes
        response.should redirect_to(EscReply.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved esc_reply as @esc_reply" do
        # Trigger the behavior that occurs when invalid params are submitted
        EscReply.any_instance.stub(:save).and_return(false)
        post :create, :esc_reply => {}
        assigns(:esc_reply).should be_a_new(EscReply)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        EscReply.any_instance.stub(:save).and_return(false)
        post :create, :esc_reply => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested esc_reply" do
        esc_reply = EscReply.create! valid_attributes
        # Assuming there are no other esc_replies in the database, this
        # specifies that the EscReply created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        EscReply.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => esc_reply.id, :esc_reply => {'these' => 'params'}
      end

      it "assigns the requested esc_reply as @esc_reply" do
        esc_reply = EscReply.create! valid_attributes
        put :update, :id => esc_reply.id, :esc_reply => valid_attributes
        assigns(:esc_reply).should eq(esc_reply)
      end

      it "redirects to the esc_reply" do
        esc_reply = EscReply.create! valid_attributes
        put :update, :id => esc_reply.id, :esc_reply => valid_attributes
        response.should redirect_to(esc_reply)
      end
    end

    describe "with invalid params" do
      it "assigns the esc_reply as @esc_reply" do
        esc_reply = EscReply.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        EscReply.any_instance.stub(:save).and_return(false)
        put :update, :id => esc_reply.id, :esc_reply => {}
        assigns(:esc_reply).should eq(esc_reply)
      end

      it "re-renders the 'edit' template" do
        esc_reply = EscReply.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        EscReply.any_instance.stub(:save).and_return(false)
        put :update, :id => esc_reply.id, :esc_reply => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested esc_reply" do
      esc_reply = EscReply.create! valid_attributes
      expect {
        delete :destroy, :id => esc_reply.id
      }.to change(EscReply, :count).by(-1)
    end

    it "redirects to the esc_replies list" do
      esc_reply = EscReply.create! valid_attributes
      delete :destroy, :id => esc_reply.id
      response.should redirect_to(esc_replies_url)
    end
  end

end
