require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe EscsController do

  # This should return the minimal set of attributes required to create a valid
  # Esc. As you add validations to Esc, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all escs as @escs" do
      esc = Esc.create! valid_attributes
      get :index
      assigns(:escs).should eq([esc])
    end
  end

  describe "GET show" do
    it "assigns the requested esc as @esc" do
      esc = Esc.create! valid_attributes
      get :show, :id => esc.id
      assigns(:esc).should eq(esc)
    end
  end

  describe "GET new" do
    it "assigns a new esc as @esc" do
      get :new
      assigns(:esc).should be_a_new(Esc)
    end
  end

  describe "GET edit" do
    it "assigns the requested esc as @esc" do
      esc = Esc.create! valid_attributes
      get :edit, :id => esc.id
      assigns(:esc).should eq(esc)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Esc" do
        expect {
          post :create, :esc => valid_attributes
        }.to change(Esc, :count).by(1)
      end

      it "assigns a newly created esc as @esc" do
        post :create, :esc => valid_attributes
        assigns(:esc).should be_a(Esc)
        assigns(:esc).should be_persisted
      end

      it "redirects to the created esc" do
        post :create, :esc => valid_attributes
        response.should redirect_to(Esc.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved esc as @esc" do
        # Trigger the behavior that occurs when invalid params are submitted
        Esc.any_instance.stub(:save).and_return(false)
        post :create, :esc => {}
        assigns(:esc).should be_a_new(Esc)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Esc.any_instance.stub(:save).and_return(false)
        post :create, :esc => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested esc" do
        esc = Esc.create! valid_attributes
        # Assuming there are no other escs in the database, this
        # specifies that the Esc created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Esc.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => esc.id, :esc => {'these' => 'params'}
      end

      it "assigns the requested esc as @esc" do
        esc = Esc.create! valid_attributes
        put :update, :id => esc.id, :esc => valid_attributes
        assigns(:esc).should eq(esc)
      end

      it "redirects to the esc" do
        esc = Esc.create! valid_attributes
        put :update, :id => esc.id, :esc => valid_attributes
        response.should redirect_to(esc)
      end
    end

    describe "with invalid params" do
      it "assigns the esc as @esc" do
        esc = Esc.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Esc.any_instance.stub(:save).and_return(false)
        put :update, :id => esc.id, :esc => {}
        assigns(:esc).should eq(esc)
      end

      it "re-renders the 'edit' template" do
        esc = Esc.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Esc.any_instance.stub(:save).and_return(false)
        put :update, :id => esc.id, :esc => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested esc" do
      esc = Esc.create! valid_attributes
      expect {
        delete :destroy, :id => esc.id
      }.to change(Esc, :count).by(-1)
    end

    it "redirects to the escs list" do
      esc = Esc.create! valid_attributes
      delete :destroy, :id => esc.id
      response.should redirect_to(escs_url)
    end
  end

end
