require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe IndustriesController do

  # This should return the minimal set of attributes required to create a valid
  # Industry. As you add validations to Industry, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all industries as @industries" do
      industry = Industry.create! valid_attributes
      get :index
      assigns(:industries).should eq([industry])
    end
  end

  describe "GET show" do
    it "assigns the requested industry as @industry" do
      industry = Industry.create! valid_attributes
      get :show, :id => industry.id
      assigns(:industry).should eq(industry)
    end
  end

  describe "GET new" do
    it "assigns a new industry as @industry" do
      get :new
      assigns(:industry).should be_a_new(Industry)
    end
  end

  describe "GET edit" do
    it "assigns the requested industry as @industry" do
      industry = Industry.create! valid_attributes
      get :edit, :id => industry.id
      assigns(:industry).should eq(industry)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Industry" do
        expect {
          post :create, :industry => valid_attributes
        }.to change(Industry, :count).by(1)
      end

      it "assigns a newly created industry as @industry" do
        post :create, :industry => valid_attributes
        assigns(:industry).should be_a(Industry)
        assigns(:industry).should be_persisted
      end

      it "redirects to the created industry" do
        post :create, :industry => valid_attributes
        response.should redirect_to(Industry.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved industry as @industry" do
        # Trigger the behavior that occurs when invalid params are submitted
        Industry.any_instance.stub(:save).and_return(false)
        post :create, :industry => {}
        assigns(:industry).should be_a_new(Industry)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Industry.any_instance.stub(:save).and_return(false)
        post :create, :industry => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested industry" do
        industry = Industry.create! valid_attributes
        # Assuming there are no other industries in the database, this
        # specifies that the Industry created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Industry.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => industry.id, :industry => {'these' => 'params'}
      end

      it "assigns the requested industry as @industry" do
        industry = Industry.create! valid_attributes
        put :update, :id => industry.id, :industry => valid_attributes
        assigns(:industry).should eq(industry)
      end

      it "redirects to the industry" do
        industry = Industry.create! valid_attributes
        put :update, :id => industry.id, :industry => valid_attributes
        response.should redirect_to(industry)
      end
    end

    describe "with invalid params" do
      it "assigns the industry as @industry" do
        industry = Industry.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Industry.any_instance.stub(:save).and_return(false)
        put :update, :id => industry.id, :industry => {}
        assigns(:industry).should eq(industry)
      end

      it "re-renders the 'edit' template" do
        industry = Industry.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Industry.any_instance.stub(:save).and_return(false)
        put :update, :id => industry.id, :industry => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested industry" do
      industry = Industry.create! valid_attributes
      expect {
        delete :destroy, :id => industry.id
      }.to change(Industry, :count).by(-1)
    end

    it "redirects to the industries list" do
      industry = Industry.create! valid_attributes
      delete :destroy, :id => industry.id
      response.should redirect_to(industries_url)
    end
  end

end
