require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe PanicBuyingsController do

  # This should return the minimal set of attributes required to create a valid
  # PanicBuying. As you add validations to PanicBuying, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all panic_buyings as @panic_buyings" do
      panic_buying = PanicBuying.create! valid_attributes
      get :index
      assigns(:panic_buyings).should eq([panic_buying])
    end
  end

  describe "GET show" do
    it "assigns the requested panic_buying as @panic_buying" do
      panic_buying = PanicBuying.create! valid_attributes
      get :show, :id => panic_buying.id
      assigns(:panic_buying).should eq(panic_buying)
    end
  end

  describe "GET new" do
    it "assigns a new panic_buying as @panic_buying" do
      get :new
      assigns(:panic_buying).should be_a_new(PanicBuying)
    end
  end

  describe "GET edit" do
    it "assigns the requested panic_buying as @panic_buying" do
      panic_buying = PanicBuying.create! valid_attributes
      get :edit, :id => panic_buying.id
      assigns(:panic_buying).should eq(panic_buying)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new PanicBuying" do
        expect {
          post :create, :panic_buying => valid_attributes
        }.to change(PanicBuying, :count).by(1)
      end

      it "assigns a newly created panic_buying as @panic_buying" do
        post :create, :panic_buying => valid_attributes
        assigns(:panic_buying).should be_a(PanicBuying)
        assigns(:panic_buying).should be_persisted
      end

      it "redirects to the created panic_buying" do
        post :create, :panic_buying => valid_attributes
        response.should redirect_to(PanicBuying.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved panic_buying as @panic_buying" do
        # Trigger the behavior that occurs when invalid params are submitted
        PanicBuying.any_instance.stub(:save).and_return(false)
        post :create, :panic_buying => {}
        assigns(:panic_buying).should be_a_new(PanicBuying)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        PanicBuying.any_instance.stub(:save).and_return(false)
        post :create, :panic_buying => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested panic_buying" do
        panic_buying = PanicBuying.create! valid_attributes
        # Assuming there are no other panic_buyings in the database, this
        # specifies that the PanicBuying created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        PanicBuying.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => panic_buying.id, :panic_buying => {'these' => 'params'}
      end

      it "assigns the requested panic_buying as @panic_buying" do
        panic_buying = PanicBuying.create! valid_attributes
        put :update, :id => panic_buying.id, :panic_buying => valid_attributes
        assigns(:panic_buying).should eq(panic_buying)
      end

      it "redirects to the panic_buying" do
        panic_buying = PanicBuying.create! valid_attributes
        put :update, :id => panic_buying.id, :panic_buying => valid_attributes
        response.should redirect_to(panic_buying)
      end
    end

    describe "with invalid params" do
      it "assigns the panic_buying as @panic_buying" do
        panic_buying = PanicBuying.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        PanicBuying.any_instance.stub(:save).and_return(false)
        put :update, :id => panic_buying.id, :panic_buying => {}
        assigns(:panic_buying).should eq(panic_buying)
      end

      it "re-renders the 'edit' template" do
        panic_buying = PanicBuying.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        PanicBuying.any_instance.stub(:save).and_return(false)
        put :update, :id => panic_buying.id, :panic_buying => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested panic_buying" do
      panic_buying = PanicBuying.create! valid_attributes
      expect {
        delete :destroy, :id => panic_buying.id
      }.to change(PanicBuying, :count).by(-1)
    end

    it "redirects to the panic_buyings list" do
      panic_buying = PanicBuying.create! valid_attributes
      delete :destroy, :id => panic_buying.id
      response.should redirect_to(panic_buyings_url)
    end
  end

end
