require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe PersonExtendsController do

  # This should return the minimal set of attributes required to create a valid
  # PersonExtend. As you add validations to PersonExtend, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all person_extends as @person_extends" do
      person_extend = PersonExtend.create! valid_attributes
      get :index
      assigns(:person_extends).should eq([person_extend])
    end
  end

  describe "GET show" do
    it "assigns the requested person_extend as @person_extend" do
      person_extend = PersonExtend.create! valid_attributes
      get :show, :id => person_extend.id
      assigns(:person_extend).should eq(person_extend)
    end
  end

  describe "GET new" do
    it "assigns a new person_extend as @person_extend" do
      get :new
      assigns(:person_extend).should be_a_new(PersonExtend)
    end
  end

  describe "GET edit" do
    it "assigns the requested person_extend as @person_extend" do
      person_extend = PersonExtend.create! valid_attributes
      get :edit, :id => person_extend.id
      assigns(:person_extend).should eq(person_extend)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new PersonExtend" do
        expect {
          post :create, :person_extend => valid_attributes
        }.to change(PersonExtend, :count).by(1)
      end

      it "assigns a newly created person_extend as @person_extend" do
        post :create, :person_extend => valid_attributes
        assigns(:person_extend).should be_a(PersonExtend)
        assigns(:person_extend).should be_persisted
      end

      it "redirects to the created person_extend" do
        post :create, :person_extend => valid_attributes
        response.should redirect_to(PersonExtend.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved person_extend as @person_extend" do
        # Trigger the behavior that occurs when invalid params are submitted
        PersonExtend.any_instance.stub(:save).and_return(false)
        post :create, :person_extend => {}
        assigns(:person_extend).should be_a_new(PersonExtend)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        PersonExtend.any_instance.stub(:save).and_return(false)
        post :create, :person_extend => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested person_extend" do
        person_extend = PersonExtend.create! valid_attributes
        # Assuming there are no other person_extends in the database, this
        # specifies that the PersonExtend created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        PersonExtend.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => person_extend.id, :person_extend => {'these' => 'params'}
      end

      it "assigns the requested person_extend as @person_extend" do
        person_extend = PersonExtend.create! valid_attributes
        put :update, :id => person_extend.id, :person_extend => valid_attributes
        assigns(:person_extend).should eq(person_extend)
      end

      it "redirects to the person_extend" do
        person_extend = PersonExtend.create! valid_attributes
        put :update, :id => person_extend.id, :person_extend => valid_attributes
        response.should redirect_to(person_extend)
      end
    end

    describe "with invalid params" do
      it "assigns the person_extend as @person_extend" do
        person_extend = PersonExtend.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        PersonExtend.any_instance.stub(:save).and_return(false)
        put :update, :id => person_extend.id, :person_extend => {}
        assigns(:person_extend).should eq(person_extend)
      end

      it "re-renders the 'edit' template" do
        person_extend = PersonExtend.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        PersonExtend.any_instance.stub(:save).and_return(false)
        put :update, :id => person_extend.id, :person_extend => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested person_extend" do
      person_extend = PersonExtend.create! valid_attributes
      expect {
        delete :destroy, :id => person_extend.id
      }.to change(PersonExtend, :count).by(-1)
    end

    it "redirects to the person_extends list" do
      person_extend = PersonExtend.create! valid_attributes
      delete :destroy, :id => person_extend.id
      response.should redirect_to(person_extends_url)
    end
  end

end
