require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe PickUpsController do

  # This should return the minimal set of attributes required to create a valid
  # PickUp. As you add validations to PickUp, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all pick_ups as @pick_ups" do
      pick_up = PickUp.create! valid_attributes
      get :index
      assigns(:pick_ups).should eq([pick_up])
    end
  end

  describe "GET show" do
    it "assigns the requested pick_up as @pick_up" do
      pick_up = PickUp.create! valid_attributes
      get :show, :id => pick_up.id
      assigns(:pick_up).should eq(pick_up)
    end
  end

  describe "GET new" do
    it "assigns a new pick_up as @pick_up" do
      get :new
      assigns(:pick_up).should be_a_new(PickUp)
    end
  end

  describe "GET edit" do
    it "assigns the requested pick_up as @pick_up" do
      pick_up = PickUp.create! valid_attributes
      get :edit, :id => pick_up.id
      assigns(:pick_up).should eq(pick_up)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new PickUp" do
        expect {
          post :create, :pick_up => valid_attributes
        }.to change(PickUp, :count).by(1)
      end

      it "assigns a newly created pick_up as @pick_up" do
        post :create, :pick_up => valid_attributes
        assigns(:pick_up).should be_a(PickUp)
        assigns(:pick_up).should be_persisted
      end

      it "redirects to the created pick_up" do
        post :create, :pick_up => valid_attributes
        response.should redirect_to(PickUp.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved pick_up as @pick_up" do
        # Trigger the behavior that occurs when invalid params are submitted
        PickUp.any_instance.stub(:save).and_return(false)
        post :create, :pick_up => {}
        assigns(:pick_up).should be_a_new(PickUp)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        PickUp.any_instance.stub(:save).and_return(false)
        post :create, :pick_up => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested pick_up" do
        pick_up = PickUp.create! valid_attributes
        # Assuming there are no other pick_ups in the database, this
        # specifies that the PickUp created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        PickUp.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => pick_up.id, :pick_up => {'these' => 'params'}
      end

      it "assigns the requested pick_up as @pick_up" do
        pick_up = PickUp.create! valid_attributes
        put :update, :id => pick_up.id, :pick_up => valid_attributes
        assigns(:pick_up).should eq(pick_up)
      end

      it "redirects to the pick_up" do
        pick_up = PickUp.create! valid_attributes
        put :update, :id => pick_up.id, :pick_up => valid_attributes
        response.should redirect_to(pick_up)
      end
    end

    describe "with invalid params" do
      it "assigns the pick_up as @pick_up" do
        pick_up = PickUp.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        PickUp.any_instance.stub(:save).and_return(false)
        put :update, :id => pick_up.id, :pick_up => {}
        assigns(:pick_up).should eq(pick_up)
      end

      it "re-renders the 'edit' template" do
        pick_up = PickUp.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        PickUp.any_instance.stub(:save).and_return(false)
        put :update, :id => pick_up.id, :pick_up => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested pick_up" do
      pick_up = PickUp.create! valid_attributes
      expect {
        delete :destroy, :id => pick_up.id
      }.to change(PickUp, :count).by(-1)
    end

    it "redirects to the pick_ups list" do
      pick_up = PickUp.create! valid_attributes
      delete :destroy, :id => pick_up.id
      response.should redirect_to(pick_ups_url)
    end
  end

end
