require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe ProcedureRoleshipsController do

  # This should return the minimal set of attributes required to create a valid
  # ProcedureRoleship. As you add validations to ProcedureRoleship, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all procedure_roleships as @procedure_roleships" do
      procedure_roleship = ProcedureRoleship.create! valid_attributes
      get :index
      assigns(:procedure_roleships).should eq([procedure_roleship])
    end
  end

  describe "GET show" do
    it "assigns the requested procedure_roleship as @procedure_roleship" do
      procedure_roleship = ProcedureRoleship.create! valid_attributes
      get :show, :id => procedure_roleship.id
      assigns(:procedure_roleship).should eq(procedure_roleship)
    end
  end

  describe "GET new" do
    it "assigns a new procedure_roleship as @procedure_roleship" do
      get :new
      assigns(:procedure_roleship).should be_a_new(ProcedureRoleship)
    end
  end

  describe "GET edit" do
    it "assigns the requested procedure_roleship as @procedure_roleship" do
      procedure_roleship = ProcedureRoleship.create! valid_attributes
      get :edit, :id => procedure_roleship.id
      assigns(:procedure_roleship).should eq(procedure_roleship)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new ProcedureRoleship" do
        expect {
          post :create, :procedure_roleship => valid_attributes
        }.to change(ProcedureRoleship, :count).by(1)
      end

      it "assigns a newly created procedure_roleship as @procedure_roleship" do
        post :create, :procedure_roleship => valid_attributes
        assigns(:procedure_roleship).should be_a(ProcedureRoleship)
        assigns(:procedure_roleship).should be_persisted
      end

      it "redirects to the created procedure_roleship" do
        post :create, :procedure_roleship => valid_attributes
        response.should redirect_to(ProcedureRoleship.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved procedure_roleship as @procedure_roleship" do
        # Trigger the behavior that occurs when invalid params are submitted
        ProcedureRoleship.any_instance.stub(:save).and_return(false)
        post :create, :procedure_roleship => {}
        assigns(:procedure_roleship).should be_a_new(ProcedureRoleship)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        ProcedureRoleship.any_instance.stub(:save).and_return(false)
        post :create, :procedure_roleship => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested procedure_roleship" do
        procedure_roleship = ProcedureRoleship.create! valid_attributes
        # Assuming there are no other procedure_roleships in the database, this
        # specifies that the ProcedureRoleship created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        ProcedureRoleship.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => procedure_roleship.id, :procedure_roleship => {'these' => 'params'}
      end

      it "assigns the requested procedure_roleship as @procedure_roleship" do
        procedure_roleship = ProcedureRoleship.create! valid_attributes
        put :update, :id => procedure_roleship.id, :procedure_roleship => valid_attributes
        assigns(:procedure_roleship).should eq(procedure_roleship)
      end

      it "redirects to the procedure_roleship" do
        procedure_roleship = ProcedureRoleship.create! valid_attributes
        put :update, :id => procedure_roleship.id, :procedure_roleship => valid_attributes
        response.should redirect_to(procedure_roleship)
      end
    end

    describe "with invalid params" do
      it "assigns the procedure_roleship as @procedure_roleship" do
        procedure_roleship = ProcedureRoleship.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        ProcedureRoleship.any_instance.stub(:save).and_return(false)
        put :update, :id => procedure_roleship.id, :procedure_roleship => {}
        assigns(:procedure_roleship).should eq(procedure_roleship)
      end

      it "re-renders the 'edit' template" do
        procedure_roleship = ProcedureRoleship.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        ProcedureRoleship.any_instance.stub(:save).and_return(false)
        put :update, :id => procedure_roleship.id, :procedure_roleship => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested procedure_roleship" do
      procedure_roleship = ProcedureRoleship.create! valid_attributes
      expect {
        delete :destroy, :id => procedure_roleship.id
      }.to change(ProcedureRoleship, :count).by(-1)
    end

    it "redirects to the procedure_roleships list" do
      procedure_roleship = ProcedureRoleship.create! valid_attributes
      delete :destroy, :id => procedure_roleship.id
      response.should redirect_to(procedure_roleships_url)
    end
  end

end
