require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe ProductCategoriesController do

  # This should return the minimal set of attributes required to create a valid
  # ProductCategory. As you add validations to ProductCategory, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all product_categories as @product_categories" do
      product_category = ProductCategory.create! valid_attributes
      get :index
      assigns(:product_categories).should eq([product_category])
    end
  end

  describe "GET show" do
    it "assigns the requested product_category as @product_category" do
      product_category = ProductCategory.create! valid_attributes
      get :show, :id => product_category.id
      assigns(:product_category).should eq(product_category)
    end
  end

  describe "GET new" do
    it "assigns a new product_category as @product_category" do
      get :new
      assigns(:product_category).should be_a_new(ProductCategory)
    end
  end

  describe "GET edit" do
    it "assigns the requested product_category as @product_category" do
      product_category = ProductCategory.create! valid_attributes
      get :edit, :id => product_category.id
      assigns(:product_category).should eq(product_category)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new ProductCategory" do
        expect {
          post :create, :product_category => valid_attributes
        }.to change(ProductCategory, :count).by(1)
      end

      it "assigns a newly created product_category as @product_category" do
        post :create, :product_category => valid_attributes
        assigns(:product_category).should be_a(ProductCategory)
        assigns(:product_category).should be_persisted
      end

      it "redirects to the created product_category" do
        post :create, :product_category => valid_attributes
        response.should redirect_to(ProductCategory.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved product_category as @product_category" do
        # Trigger the behavior that occurs when invalid params are submitted
        ProductCategory.any_instance.stub(:save).and_return(false)
        post :create, :product_category => {}
        assigns(:product_category).should be_a_new(ProductCategory)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        ProductCategory.any_instance.stub(:save).and_return(false)
        post :create, :product_category => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested product_category" do
        product_category = ProductCategory.create! valid_attributes
        # Assuming there are no other product_categories in the database, this
        # specifies that the ProductCategory created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        ProductCategory.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => product_category.id, :product_category => {'these' => 'params'}
      end

      it "assigns the requested product_category as @product_category" do
        product_category = ProductCategory.create! valid_attributes
        put :update, :id => product_category.id, :product_category => valid_attributes
        assigns(:product_category).should eq(product_category)
      end

      it "redirects to the product_category" do
        product_category = ProductCategory.create! valid_attributes
        put :update, :id => product_category.id, :product_category => valid_attributes
        response.should redirect_to(product_category)
      end
    end

    describe "with invalid params" do
      it "assigns the product_category as @product_category" do
        product_category = ProductCategory.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        ProductCategory.any_instance.stub(:save).and_return(false)
        put :update, :id => product_category.id, :product_category => {}
        assigns(:product_category).should eq(product_category)
      end

      it "re-renders the 'edit' template" do
        product_category = ProductCategory.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        ProductCategory.any_instance.stub(:save).and_return(false)
        put :update, :id => product_category.id, :product_category => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested product_category" do
      product_category = ProductCategory.create! valid_attributes
      expect {
        delete :destroy, :id => product_category.id
      }.to change(ProductCategory, :count).by(-1)
    end

    it "redirects to the product_categories list" do
      product_category = ProductCategory.create! valid_attributes
      delete :destroy, :id => product_category.id
      response.should redirect_to(product_categories_url)
    end
  end

end
