require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe ProdDelOrdshipsController do

  # This should return the minimal set of attributes required to create a valid
  # ProdDelOrdship. As you add validations to ProdDelOrdship, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all prod_del_ordships as @prod_del_ordships" do
      prod_del_ordship = ProdDelOrdship.create! valid_attributes
      get :index
      assigns(:prod_del_ordships).should eq([prod_del_ordship])
    end
  end

  describe "GET show" do
    it "assigns the requested prod_del_ordship as @prod_del_ordship" do
      prod_del_ordship = ProdDelOrdship.create! valid_attributes
      get :show, :id => prod_del_ordship.id
      assigns(:prod_del_ordship).should eq(prod_del_ordship)
    end
  end

  describe "GET new" do
    it "assigns a new prod_del_ordship as @prod_del_ordship" do
      get :new
      assigns(:prod_del_ordship).should be_a_new(ProdDelOrdship)
    end
  end

  describe "GET edit" do
    it "assigns the requested prod_del_ordship as @prod_del_ordship" do
      prod_del_ordship = ProdDelOrdship.create! valid_attributes
      get :edit, :id => prod_del_ordship.id
      assigns(:prod_del_ordship).should eq(prod_del_ordship)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new ProdDelOrdship" do
        expect {
          post :create, :prod_del_ordship => valid_attributes
        }.to change(ProdDelOrdship, :count).by(1)
      end

      it "assigns a newly created prod_del_ordship as @prod_del_ordship" do
        post :create, :prod_del_ordship => valid_attributes
        assigns(:prod_del_ordship).should be_a(ProdDelOrdship)
        assigns(:prod_del_ordship).should be_persisted
      end

      it "redirects to the created prod_del_ordship" do
        post :create, :prod_del_ordship => valid_attributes
        response.should redirect_to(ProdDelOrdship.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved prod_del_ordship as @prod_del_ordship" do
        # Trigger the behavior that occurs when invalid params are submitted
        ProdDelOrdship.any_instance.stub(:save).and_return(false)
        post :create, :prod_del_ordship => {}
        assigns(:prod_del_ordship).should be_a_new(ProdDelOrdship)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        ProdDelOrdship.any_instance.stub(:save).and_return(false)
        post :create, :prod_del_ordship => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested prod_del_ordship" do
        prod_del_ordship = ProdDelOrdship.create! valid_attributes
        # Assuming there are no other prod_del_ordships in the database, this
        # specifies that the ProdDelOrdship created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        ProdDelOrdship.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => prod_del_ordship.id, :prod_del_ordship => {'these' => 'params'}
      end

      it "assigns the requested prod_del_ordship as @prod_del_ordship" do
        prod_del_ordship = ProdDelOrdship.create! valid_attributes
        put :update, :id => prod_del_ordship.id, :prod_del_ordship => valid_attributes
        assigns(:prod_del_ordship).should eq(prod_del_ordship)
      end

      it "redirects to the prod_del_ordship" do
        prod_del_ordship = ProdDelOrdship.create! valid_attributes
        put :update, :id => prod_del_ordship.id, :prod_del_ordship => valid_attributes
        response.should redirect_to(prod_del_ordship)
      end
    end

    describe "with invalid params" do
      it "assigns the prod_del_ordship as @prod_del_ordship" do
        prod_del_ordship = ProdDelOrdship.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        ProdDelOrdship.any_instance.stub(:save).and_return(false)
        put :update, :id => prod_del_ordship.id, :prod_del_ordship => {}
        assigns(:prod_del_ordship).should eq(prod_del_ordship)
      end

      it "re-renders the 'edit' template" do
        prod_del_ordship = ProdDelOrdship.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        ProdDelOrdship.any_instance.stub(:save).and_return(false)
        put :update, :id => prod_del_ordship.id, :prod_del_ordship => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested prod_del_ordship" do
      prod_del_ordship = ProdDelOrdship.create! valid_attributes
      expect {
        delete :destroy, :id => prod_del_ordship.id
      }.to change(ProdDelOrdship, :count).by(-1)
    end

    it "redirects to the prod_del_ordships list" do
      prod_del_ordship = ProdDelOrdship.create! valid_attributes
      delete :destroy, :id => prod_del_ordship.id
      response.should redirect_to(prod_del_ordships_url)
    end
  end

end
