require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe SkuCategoriesController do

  # This should return the minimal set of attributes required to create a valid
  # SkuCategory. As you add validations to SkuCategory, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all sku_categories as @sku_categories" do
      sku_category = SkuCategory.create! valid_attributes
      get :index
      assigns(:sku_categories).should eq([sku_category])
    end
  end

  describe "GET show" do
    it "assigns the requested sku_category as @sku_category" do
      sku_category = SkuCategory.create! valid_attributes
      get :show, :id => sku_category.id
      assigns(:sku_category).should eq(sku_category)
    end
  end

  describe "GET new" do
    it "assigns a new sku_category as @sku_category" do
      get :new
      assigns(:sku_category).should be_a_new(SkuCategory)
    end
  end

  describe "GET edit" do
    it "assigns the requested sku_category as @sku_category" do
      sku_category = SkuCategory.create! valid_attributes
      get :edit, :id => sku_category.id
      assigns(:sku_category).should eq(sku_category)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new SkuCategory" do
        expect {
          post :create, :sku_category => valid_attributes
        }.to change(SkuCategory, :count).by(1)
      end

      it "assigns a newly created sku_category as @sku_category" do
        post :create, :sku_category => valid_attributes
        assigns(:sku_category).should be_a(SkuCategory)
        assigns(:sku_category).should be_persisted
      end

      it "redirects to the created sku_category" do
        post :create, :sku_category => valid_attributes
        response.should redirect_to(SkuCategory.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved sku_category as @sku_category" do
        # Trigger the behavior that occurs when invalid params are submitted
        SkuCategory.any_instance.stub(:save).and_return(false)
        post :create, :sku_category => {}
        assigns(:sku_category).should be_a_new(SkuCategory)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        SkuCategory.any_instance.stub(:save).and_return(false)
        post :create, :sku_category => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested sku_category" do
        sku_category = SkuCategory.create! valid_attributes
        # Assuming there are no other sku_categories in the database, this
        # specifies that the SkuCategory created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        SkuCategory.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => sku_category.id, :sku_category => {'these' => 'params'}
      end

      it "assigns the requested sku_category as @sku_category" do
        sku_category = SkuCategory.create! valid_attributes
        put :update, :id => sku_category.id, :sku_category => valid_attributes
        assigns(:sku_category).should eq(sku_category)
      end

      it "redirects to the sku_category" do
        sku_category = SkuCategory.create! valid_attributes
        put :update, :id => sku_category.id, :sku_category => valid_attributes
        response.should redirect_to(sku_category)
      end
    end

    describe "with invalid params" do
      it "assigns the sku_category as @sku_category" do
        sku_category = SkuCategory.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        SkuCategory.any_instance.stub(:save).and_return(false)
        put :update, :id => sku_category.id, :sku_category => {}
        assigns(:sku_category).should eq(sku_category)
      end

      it "re-renders the 'edit' template" do
        sku_category = SkuCategory.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        SkuCategory.any_instance.stub(:save).and_return(false)
        put :update, :id => sku_category.id, :sku_category => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested sku_category" do
      sku_category = SkuCategory.create! valid_attributes
      expect {
        delete :destroy, :id => sku_category.id
      }.to change(SkuCategory, :count).by(-1)
    end

    it "redirects to the sku_categories list" do
      sku_category = SkuCategory.create! valid_attributes
      delete :destroy, :id => sku_category.id
      response.should redirect_to(sku_categories_url)
    end
  end

end
