require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe SkuImagesController do

  # This should return the minimal set of attributes required to create a valid
  # SkuImage. As you add validations to SkuImage, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all sku_images as @sku_images" do
      sku_image = SkuImage.create! valid_attributes
      get :index
      assigns(:sku_images).should eq([sku_image])
    end
  end

  describe "GET show" do
    it "assigns the requested sku_image as @sku_image" do
      sku_image = SkuImage.create! valid_attributes
      get :show, :id => sku_image.id
      assigns(:sku_image).should eq(sku_image)
    end
  end

  describe "GET new" do
    it "assigns a new sku_image as @sku_image" do
      get :new
      assigns(:sku_image).should be_a_new(SkuImage)
    end
  end

  describe "GET edit" do
    it "assigns the requested sku_image as @sku_image" do
      sku_image = SkuImage.create! valid_attributes
      get :edit, :id => sku_image.id
      assigns(:sku_image).should eq(sku_image)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new SkuImage" do
        expect {
          post :create, :sku_image => valid_attributes
        }.to change(SkuImage, :count).by(1)
      end

      it "assigns a newly created sku_image as @sku_image" do
        post :create, :sku_image => valid_attributes
        assigns(:sku_image).should be_a(SkuImage)
        assigns(:sku_image).should be_persisted
      end

      it "redirects to the created sku_image" do
        post :create, :sku_image => valid_attributes
        response.should redirect_to(SkuImage.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved sku_image as @sku_image" do
        # Trigger the behavior that occurs when invalid params are submitted
        SkuImage.any_instance.stub(:save).and_return(false)
        post :create, :sku_image => {}
        assigns(:sku_image).should be_a_new(SkuImage)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        SkuImage.any_instance.stub(:save).and_return(false)
        post :create, :sku_image => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested sku_image" do
        sku_image = SkuImage.create! valid_attributes
        # Assuming there are no other sku_images in the database, this
        # specifies that the SkuImage created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        SkuImage.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => sku_image.id, :sku_image => {'these' => 'params'}
      end

      it "assigns the requested sku_image as @sku_image" do
        sku_image = SkuImage.create! valid_attributes
        put :update, :id => sku_image.id, :sku_image => valid_attributes
        assigns(:sku_image).should eq(sku_image)
      end

      it "redirects to the sku_image" do
        sku_image = SkuImage.create! valid_attributes
        put :update, :id => sku_image.id, :sku_image => valid_attributes
        response.should redirect_to(sku_image)
      end
    end

    describe "with invalid params" do
      it "assigns the sku_image as @sku_image" do
        sku_image = SkuImage.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        SkuImage.any_instance.stub(:save).and_return(false)
        put :update, :id => sku_image.id, :sku_image => {}
        assigns(:sku_image).should eq(sku_image)
      end

      it "re-renders the 'edit' template" do
        sku_image = SkuImage.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        SkuImage.any_instance.stub(:save).and_return(false)
        put :update, :id => sku_image.id, :sku_image => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested sku_image" do
      sku_image = SkuImage.create! valid_attributes
      expect {
        delete :destroy, :id => sku_image.id
      }.to change(SkuImage, :count).by(-1)
    end

    it "redirects to the sku_images list" do
      sku_image = SkuImage.create! valid_attributes
      delete :destroy, :id => sku_image.id
      response.should redirect_to(sku_images_url)
    end
  end

end
