require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe SkuProductshipsController do

  # This should return the minimal set of attributes required to create a valid
  # SkuProductship. As you add validations to SkuProductship, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all sku_productships as @sku_productships" do
      sku_productship = SkuProductship.create! valid_attributes
      get :index
      assigns(:sku_productships).should eq([sku_productship])
    end
  end

  describe "GET show" do
    it "assigns the requested sku_productship as @sku_productship" do
      sku_productship = SkuProductship.create! valid_attributes
      get :show, :id => sku_productship.id
      assigns(:sku_productship).should eq(sku_productship)
    end
  end

  describe "GET new" do
    it "assigns a new sku_productship as @sku_productship" do
      get :new
      assigns(:sku_productship).should be_a_new(SkuProductship)
    end
  end

  describe "GET edit" do
    it "assigns the requested sku_productship as @sku_productship" do
      sku_productship = SkuProductship.create! valid_attributes
      get :edit, :id => sku_productship.id
      assigns(:sku_productship).should eq(sku_productship)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new SkuProductship" do
        expect {
          post :create, :sku_productship => valid_attributes
        }.to change(SkuProductship, :count).by(1)
      end

      it "assigns a newly created sku_productship as @sku_productship" do
        post :create, :sku_productship => valid_attributes
        assigns(:sku_productship).should be_a(SkuProductship)
        assigns(:sku_productship).should be_persisted
      end

      it "redirects to the created sku_productship" do
        post :create, :sku_productship => valid_attributes
        response.should redirect_to(SkuProductship.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved sku_productship as @sku_productship" do
        # Trigger the behavior that occurs when invalid params are submitted
        SkuProductship.any_instance.stub(:save).and_return(false)
        post :create, :sku_productship => {}
        assigns(:sku_productship).should be_a_new(SkuProductship)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        SkuProductship.any_instance.stub(:save).and_return(false)
        post :create, :sku_productship => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested sku_productship" do
        sku_productship = SkuProductship.create! valid_attributes
        # Assuming there are no other sku_productships in the database, this
        # specifies that the SkuProductship created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        SkuProductship.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => sku_productship.id, :sku_productship => {'these' => 'params'}
      end

      it "assigns the requested sku_productship as @sku_productship" do
        sku_productship = SkuProductship.create! valid_attributes
        put :update, :id => sku_productship.id, :sku_productship => valid_attributes
        assigns(:sku_productship).should eq(sku_productship)
      end

      it "redirects to the sku_productship" do
        sku_productship = SkuProductship.create! valid_attributes
        put :update, :id => sku_productship.id, :sku_productship => valid_attributes
        response.should redirect_to(sku_productship)
      end
    end

    describe "with invalid params" do
      it "assigns the sku_productship as @sku_productship" do
        sku_productship = SkuProductship.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        SkuProductship.any_instance.stub(:save).and_return(false)
        put :update, :id => sku_productship.id, :sku_productship => {}
        assigns(:sku_productship).should eq(sku_productship)
      end

      it "re-renders the 'edit' template" do
        sku_productship = SkuProductship.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        SkuProductship.any_instance.stub(:save).and_return(false)
        put :update, :id => sku_productship.id, :sku_productship => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested sku_productship" do
      sku_productship = SkuProductship.create! valid_attributes
      expect {
        delete :destroy, :id => sku_productship.id
      }.to change(SkuProductship, :count).by(-1)
    end

    it "redirects to the sku_productships list" do
      sku_productship = SkuProductship.create! valid_attributes
      delete :destroy, :id => sku_productship.id
      response.should redirect_to(sku_productships_url)
    end
  end

end
