require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe StoreEntriesController do

  # This should return the minimal set of attributes required to create a valid
  # StoreEntry. As you add validations to StoreEntry, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all store_entries as @store_entries" do
      store_entry = StoreEntry.create! valid_attributes
      get :index
      assigns(:store_entries).should eq([store_entry])
    end
  end

  describe "GET show" do
    it "assigns the requested store_entry as @store_entry" do
      store_entry = StoreEntry.create! valid_attributes
      get :show, :id => store_entry.id
      assigns(:store_entry).should eq(store_entry)
    end
  end

  describe "GET new" do
    it "assigns a new store_entry as @store_entry" do
      get :new
      assigns(:store_entry).should be_a_new(StoreEntry)
    end
  end

  describe "GET edit" do
    it "assigns the requested store_entry as @store_entry" do
      store_entry = StoreEntry.create! valid_attributes
      get :edit, :id => store_entry.id
      assigns(:store_entry).should eq(store_entry)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new StoreEntry" do
        expect {
          post :create, :store_entry => valid_attributes
        }.to change(StoreEntry, :count).by(1)
      end

      it "assigns a newly created store_entry as @store_entry" do
        post :create, :store_entry => valid_attributes
        assigns(:store_entry).should be_a(StoreEntry)
        assigns(:store_entry).should be_persisted
      end

      it "redirects to the created store_entry" do
        post :create, :store_entry => valid_attributes
        response.should redirect_to(StoreEntry.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved store_entry as @store_entry" do
        # Trigger the behavior that occurs when invalid params are submitted
        StoreEntry.any_instance.stub(:save).and_return(false)
        post :create, :store_entry => {}
        assigns(:store_entry).should be_a_new(StoreEntry)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        StoreEntry.any_instance.stub(:save).and_return(false)
        post :create, :store_entry => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested store_entry" do
        store_entry = StoreEntry.create! valid_attributes
        # Assuming there are no other store_entries in the database, this
        # specifies that the StoreEntry created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        StoreEntry.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => store_entry.id, :store_entry => {'these' => 'params'}
      end

      it "assigns the requested store_entry as @store_entry" do
        store_entry = StoreEntry.create! valid_attributes
        put :update, :id => store_entry.id, :store_entry => valid_attributes
        assigns(:store_entry).should eq(store_entry)
      end

      it "redirects to the store_entry" do
        store_entry = StoreEntry.create! valid_attributes
        put :update, :id => store_entry.id, :store_entry => valid_attributes
        response.should redirect_to(store_entry)
      end
    end

    describe "with invalid params" do
      it "assigns the store_entry as @store_entry" do
        store_entry = StoreEntry.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        StoreEntry.any_instance.stub(:save).and_return(false)
        put :update, :id => store_entry.id, :store_entry => {}
        assigns(:store_entry).should eq(store_entry)
      end

      it "re-renders the 'edit' template" do
        store_entry = StoreEntry.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        StoreEntry.any_instance.stub(:save).and_return(false)
        put :update, :id => store_entry.id, :store_entry => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested store_entry" do
      store_entry = StoreEntry.create! valid_attributes
      expect {
        delete :destroy, :id => store_entry.id
      }.to change(StoreEntry, :count).by(-1)
    end

    it "redirects to the store_entries list" do
      store_entry = StoreEntry.create! valid_attributes
      delete :destroy, :id => store_entry.id
      response.should redirect_to(store_entries_url)
    end
  end

end
