product_category_1:
  id: '1'
  parent_id: ''
  number: '01_media'
  name: '图书音像'
  description: '图书音像'
  sequence: '0'
  status: 'true'
  created_at: '2012-05-24 18:08:26 +0800'
  updated_at: '2012-05-24 18:08:26 +0800'
product_category_2:
  id: '2'
  parent_id: ''
  number: '02_electric'
  name: '家用电器'
  description: ''
  sequence: '1'
  status: 'true'
  created_at: '2012-05-24 18:08:26 +0800'
  updated_at: '2012-05-24 18:08:26 +0800'
product_category_3:
  id: '3'
  parent_id: ''
  number: '03_mobile'
  name: '手机数码'
  description: ''
  sequence: '0'
  status: 'false'
  created_at: '2012-05-24 18:08:26 +0800'
  updated_at: '2012-06-04 20:51:52 +0800'
product_category_13:
  id: '13'
  parent_id: '1'
  number: '01_01'
  name: '书籍'
  description: ''
  sequence: '0'
  status: 'true'
  created_at: '2012-05-24 18:08:26 +0800'
  updated_at: '2012-06-05 17:37:38 +0800'
product_category_14:
  id: '14'
  parent_id: '1'
  number: '01_02'
  name: '音像'
  description: ''
  sequence: '0'
  status: 'true'
  created_at: '2012-05-24 18:08:26 +0800'
  updated_at: '2012-05-24 18:08:26 +0800'
product_category_15:
  id: '15'
  parent_id: '1'
  number: '01_03'
  name: '英文原版'
  description: ''
  sequence: '0'
  status: 'true'
  created_at: '2012-05-24 18:08:26 +0800'
  updated_at: '2012-05-24 18:08:26 +0800'
product_category_24:
  id: '24'
  parent_id: '13'
  number: '01_01_01'
  name: '电子书'
  description: ''
  sequence: '0'
  status: 'true'
  created_at: '2012-05-24 18:08:26 +0800'
  updated_at: '2012-05-24 18:08:26 +0800'
product_category_25:
  id: '25'
  parent_id: '13'
  number: '01_01_02'
  name: '网络原创'
  description: ''
  sequence: '0'
  status: 'true'
  created_at: '2012-05-24 18:08:26 +0800'
  updated_at: '2012-05-24 18:08:26 +0800'
product_category_26:
  id: '26'
  parent_id: '13'
  number: '01_01_03'
  name: '计算机'
  description: ''
  sequence: '0'
  status: 'true'
  created_at: '2012-05-24 18:08:26 +0800'
  updated_at: '2012-06-05 17:37:22 +0800'
product_category_27:
  id: '27'
  parent_id: '13'
  number: '01_01_04'
  name: '多媒体图书'
  description: ''
  sequence: '0'
  status: 'true'
  created_at: '2012-05-24 18:08:26 +0800'
  updated_at: '2012-05-24 18:08:26 +0800'
product_category_28:
  id: '28'
  parent_id: '14'
  number: '01_02_01'
  name: '音乐'
  description: ''
  sequence: '0'
  status: 'true'
  created_at: '2012-05-24 18:08:26 +0800'
  updated_at: '2012-05-24 18:08:26 +0800'
product_category_29:
  id: '29'
  parent_id: '14'
  number: '01_02_02'
  name: '影视'
  description: ''
  sequence: '0'
  status: 'true'
  created_at: '2012-05-24 18:08:26 +0800'
  updated_at: '2012-05-24 18:08:26 +0800'
product_category_30:
  id: '30'
  parent_id: '14'
  number: '01_02_03'
  name: '教育音像'
  description: ''
  sequence: '0'
  status: 'true'
  created_at: '2012-05-24 18:08:26 +0800'
  updated_at: '2012-05-24 18:08:26 +0800'
product_category_36:
  id: '36'
  parent_id: '2'
  number: '02_01'
  name: '大家电'
  description: ''
  sequence: '0'
  status: 'true'
  created_at: '2012-05-24 18:08:26 +0800'
  updated_at: '2012-05-24 18:08:26 +0800'
product_category_37:
  id: '37'
  parent_id: '2'
  number: '02_02'
  name: '生活电器'
  description: ''
  sequence: '0'
  status: 'true'
  created_at: '2012-05-24 18:08:26 +0800'
  updated_at: '2012-05-24 18:08:26 +0800'
product_category_38:
  id: '38'
  parent_id: '2'
  number: '02_03'
  name: '厨房电器'
  description: ''
  sequence: '0'
  status: 'true'
  created_at: '2012-05-24 18:08:26 +0800'
  updated_at: '2012-05-24 18:08:26 +0800'
