products_1:
  id: '1'
  number: 'ebook_001'
  name: '【测试数据】Taurus使用手册'
  product_category_id: '24'
  place_of_origin: ''
  unit: ''
  manufacturer: ''
  market_price: '32.5'
  tax: ''
  price_after_tax: '16.48'
  weight: '0.0'
  description: ''
  sales_status: 1
  if_shown_on_web: 1
  product_type: 0
products_2:
  id: '2'
  number: 'ebook_002'
  name: '【测试数据】Ebook全套'
  product_category_id: '24'
  place_of_origin: ''
  unit: ''
  manufacturer: ''
  market_price: '18.7'
  tax: ''
  price_after_tax: '16.0'
  weight: '0.0'
  description: ''
  sales_status: 1
  if_shown_on_web: 1
  product_type: 0
products_3:
  id: '3'
  number: 'ebook_003'
  name: '【测试数据】Ebook （上册）'
  product_category_id: '24'
  place_of_origin: ''
  unit: ''
  manufacturer: ''
  market_price: '16.0'
  tax: ''
  price_after_tax: '12.0'
  weight: '0.0'
  description: ''
  sales_status: 1
  if_shown_on_web: 1
  product_type: 0
products_4:
  id: '4'
  number: 'ebook_004'
  name: '【测试数据】Ebook （下册）'
  product_category_id: '15'
  place_of_origin: ''
  unit: ''
  manufacturer: ''
  market_price: '16.0'
  tax: ''
  price_after_tax: '12.8'
  weight: '0.0'
  description: ''
  sales_status: 1
  if_shown_on_web: 1
  product_type: 0
products_5:
  id: '5'
  number: 'audio_001'
  name: '【测试数据】Do Re Mi 学音乐 2002年版 '
  product_category_id: '28'
  place_of_origin: ''
  unit: ''
  manufacturer: ''
  market_price: '75.0'
  tax: ''
  price_after_tax: '68.7'
  weight: '0.5'
  description: ''
  sales_status: ''
  if_shown_on_web: ''
  product_type: 0
products_6:
  id: '6'
  number: 'movie_001'
  name: '【测试数据】2007年电影集锦'
  product_category_id: '29'
  place_of_origin: ''
  unit: ''
  manufacturer: ''
  market_price: '175.0'
  tax: ''
  price_after_tax: '105.0'
  weight: '0.0'
  description: ''
  sales_status: ''
  if_shown_on_web: ''
  product_type: 0
products_7:
  id: '7'
  number: 'movie_002'
  name: '【测试数据】2008年电影集锦'
  product_category_id: '29'
  place_of_origin: ''
  unit: ''
  manufacturer: ''
  market_price: '40.0'
  tax: ''
  price_after_tax: '25.0'
  weight: '0.0'
  description: ''
  sales_status: ''
  if_shown_on_web: ''
  product_type: 0
products_8:
  id: '8'
  number: 'movie_003'
  name: '【测试数据】2009年电影集锦'
  product_category_id: '29'
  place_of_origin: ''
  unit: ''
  manufacturer: ''
  market_price: '40.0'
  tax: ''
  price_after_tax: '25.0'
  weight: '0.0'
  description: ''
  sales_status: ''
  if_shown_on_web: ''
  product_type: 0
products_9:
  id: '9'
  number: 'movie_004'
  name: '【测试数据】2010年电影集锦 '
  product_category_id: '29'
  place_of_origin: ''
  unit: ''
  manufacturer: ''
  market_price: '25.0'
  tax: ''
  price_after_tax: '16.0'
  weight: '0.0'
  description: ''
  sales_status: ''
  if_shown_on_web: ''
  product_type: 0
products_10:
  id: '10'
  number: 'movie_005'
  name: '【测试数据】2011年电影集锦 '
  product_category_id: '29'
  place_of_origin: ''
  unit: ''
  manufacturer: ''
  market_price: '0.0'
  tax: ''
  price_after_tax: '16.0'
  weight: '0.0'
  description: ''
  sales_status: ''
  if_shown_on_web: ''
  product_type: 0
products_11:
  id: '11'
  number: 'movie_006'
  name: '【测试数据】2007-2011年电影集锦大合集 '
  product_category_id: '29'
  place_of_origin: ''
  unit: ''
  manufacturer: ''
  market_price: '125.0'
  tax: ''
  price_after_tax: '75.0'
  weight: '0.0'
  description: ''
  sales_status: ''
  if_shown_on_web: ''
  product_type: 0
products_12:
  id: '12'
  number: 'ebook_005'
  name: '【测试数据】Dummies Book for the IT Projects Management '
  product_category_id: '15'
  place_of_origin: ''
  unit: ''
  manufacturer: ''
  market_price: '155.8'
  tax: ''
  price_after_tax: '123.8'
  weight: '0.0'
  description: ''
  sales_status: ''
  if_shown_on_web: ''
  product_type: 0
products_13:
  id: '13'
  number: 'elec_001'
  name: '【测试数据】新示界16:9高清电视机 '
  product_category_id: '36'
  place_of_origin: ''
  unit: ''
  manufacturer: ''
  market_price: '4299.0'
  tax: ''
  price_after_tax: '3584.0'
  weight: '15.0'
  description: ''
  sales_status: ''
  if_shown_on_web: ''
  product_type: 0
products_14:
  id: '14'
  number: 'ebook_006'
  name: '【测试数据】不可思议的穿越小说 第一册 '
  product_category_id: '25'
  place_of_origin: ''
  unit: ''
  manufacturer: ''
  market_price: '2.5'
  tax: ''
  price_after_tax: '1.28'
  weight: '0.0'
  description: ''
  sales_status: ''
  if_shown_on_web: ''
  product_type: 0
products_15:
  id: '15'
  number: 'ebook_007'
  name: '【测试数据】Math Geek '
  product_category_id: '26'
  place_of_origin: ''
  unit: ''
  manufacturer: ''
  market_price: '124.7'
  tax: ''
  price_after_tax: '86.9'
  weight: '0.0'
  description: ''
  sales_status: ''
  if_shown_on_web: ''
  product_type: 0
products_16:
  id: '16'
  number: 'ebook_008'
  name: '【测试数据】七彩童话'
  product_category_id: '27'
  place_of_origin: ''
  unit: ''
  manufacturer: ''
  market_price: '0.0'
  tax: ''
  price_after_tax: '25.8'
  weight: '0.0'
  description: ''
  sales_status: ''
  if_shown_on_web: ''
  product_type: 0
products_17:
  id: '17'
  number: 'ebook_009'
  name: '【测试数据】早教一千零一问'
  product_category_id: '30'
  place_of_origin: ''
  unit: ''
  manufacturer: ''
  market_price: '0.0'
  tax: ''
  price_after_tax: '25.8'
  weight: '0.0'
  description: ''
  sales_status: ''
  if_shown_on_web: ''
  product_type: 0
products_18:
  id: '18'
  number: 'elec_002'
  name: '【测试数据】埃尔埃单门小冰箱 '
  product_category_id: '38'
  place_of_origin: ''
  unit: ''
  manufacturer: ''
  market_price: '1779.0'
  tax: ''
  price_after_tax: '1598.0'
  weight: '15.0'
  description: ''
  sales_status: ''
  if_shown_on_web: ''
  product_type: 0
products_19:
  id: '19'
  number: 'elec_003'
  name: '【测试数据】埃尔埃车载冰箱'
  product_category_id: '37'
  place_of_origin: ''
  unit: ''
  manufacturer: ''
  market_price: '228.0'
  tax: ''
  price_after_tax: '198.0'
  weight: '0.0'
  description: ''
  sales_status: ''
  if_shown_on_web: ''
  product_type: 0
products_20:
  id: '20'
  number: 'elec_004'
  name: '【测试数据】其正按摩椅'
  product_category_id: '37'
  place_of_origin: ''
  unit: ''
  manufacturer: ''
  market_price: '998.0'
  tax: ''
  price_after_tax: '898.0'
  weight: '0.0'
  description: ''
  sales_status: ''
  if_shown_on_web: ''
  product_type: 0
products_21:
  id: '21'
  number: 'elec_005'
  name: '【测试数据】埃尔埃榨汁机'
  product_category_id: '38'
  place_of_origin: ''
  unit: ''
  manufacturer: ''
  market_price: '168.0'
  tax: ''
  price_after_tax: '98.0'
  weight: '1.0'
  description: ''
  sales_status: ''
  if_shown_on_web: ''
  product_type: 0